/*
  Warnings:

  - Changed the type of `school` on the `Profile` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.
  - Changed the type of `school` on the `Project` table. No cast exists, the column would be dropped and recreated, which cannot be done if there is data, since the column is required.

*/
-- CreateEnum
CREATE TYPE "School" AS ENUM ('UNIVERSITY_OF_WASHINGTON', 'UNIVERSITY_OF_ILLINOIS_URBANA_CHAMPAIGN', 'NEW_YORK_UNIVERSITY', 'UNIVERSITY_OF_NOTRE_DAME', 'UNIVERSITY_OF_WISCONSIN_MADISON', 'UNIVERSITY_OF_CALIFORNIA_LOS_ANGELES', 'UNIVERSITY_OF_VIRGINIA', 'UNIVERSITY_OF_MINNESOTA', 'GEORGETOWN_UNIVERSITY', 'UNIVERSITY_OF_NORTH_CAROLINA_AT_CHAPEL_HILL', 'PENNSYLVANIA_STATE_UNIVERSITY', 'PURDUE_UNIVERSITY', 'UNIVERSITY_OF_COLORADO_BOULDER', 'RICE_UNIVERSITY', 'VANDERBILT_UNIVERSITY', 'UNIVERSITY_OF_MARYLAND_COLLEGE_PARK', 'UNIVERSITY_OF_CALIFORNIA_SAN_DIEGO', 'UNIVERSITY_OF_PITTSBURGH', 'UNIVERSITY_OF_IOWA', 'JOHNS_HOPKINS_UNIVERSITY', 'UNIVERSITY_OF_MIAMI', 'STANFORD_UNIVERSITY', 'HARVARD_UNIVERSITY', 'MASSACHUSETTS_INSTITUTE_OF_TECHNOLOGY', 'UNIVERSITY_OF_CALIFORNIA_BERKELEY', 'UNIVERSITY_OF_FLORIDA', 'UNIVERSITY_OF_TEXAS_AT_AUSTIN', 'PRINCETON_UNIVERSITY', 'COLUMBIA_UNIVERSITY', 'UNIVERSITY_OF_PENNSYLVANIA', 'YALE_UNIVERSITY', 'DUKE_UNIVERSITY', 'UNIVERSITY_OF_CHICAGO', 'UNIVERSITY_OF_SOUTHERN_CALIFORNIA', 'CORNELL_UNIVERSITY', 'BROWN_UNIVERSITY', 'NORTHWESTERN_UNIVERSITY', 'UNIVERSITY_OF_MICHIGAN', 'CARNEGIE_MELLON_UNIVERSITY');

-- AlterTable
ALTER TABLE "Profile" DROP COLUMN "school",
ADD COLUMN     "school" "School" NOT NULL;

-- AlterTable
ALTER TABLE "Project" DROP COLUMN "school",
ADD COLUMN     "school" "School" NOT NULL;
